name: Build and Release

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      prev_tag: ${{ steps.main.outputs.prev_tag }}
      commit: ${{ steps.main.outputs.commit }}
      fomatted_version: ${{ steps.main.outputs.fomatted_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          repository: MoeKoeMusic/MoeKoeMusic
      - id: main
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | head -n 1)
          COMMIT=$(git rev-parse --short HEAD)
          echo "prev_tag=$PREV_TAG" >> "$GITHUB_OUTPUT"
          echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"
          echo "fomatted_version=${PREV_TAG}-nightly-${COMMIT}" >> "$GITHUB_OUTPUT"

  build:
    needs: generate-version
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
          repository: MoeKoeMusic/MoeKoeMusic
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: change version
        env:
          old_version: ${{ needs.generate-version.outputs.prev_tag }}
          version: ${{ needs.generate-version.outputs.fomatted_version }}
        run: |
          echo "ℹ change version from ${{ env.old_version }} to ${{ env.version }}"
          jq --arg version "${{ env.version }}" '.version = $version' package.json > package.json.new
          mv package.json package.json.old
          mv package.json.new package.json

      - name: build
        id: build
        env:
          os: ${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'macos' || 'linux' }}
        run: |
          npm run install-all
          npm run build
          npm run electron:build:${{ env.os }}
          echo "dist-mac-arm=dist_electron/MoeKoe Music-arm64.dmg" >> "$GITHUB_OUTPUT"
          echo "dist-mac-intel=dist_electron/MoeKoe Music-x64.dmg" >> "$GITHUB_OUTPUT"
          echo "dist-linux=dist_electron/MoeKoe Music.AppImage" >> "$GITHUB_OUTPUT"
          echo "dist-linux-deb=dist_electron/MoeKoe Music.deb" >> "$GITHUB_OUTPUT"
      - name: generate release body
        run: |
          echo "> [!NOTE]  " >> release-body.md
          echo "> This is a nightly build, if you're looking for the latest version, please wait for the [official release](https://github.com/MoeKoeMusic/MoeKoeMusic/releases).  " >> release-body.md
          echo "This nightly build is based on commit [${{ needs.generate-version.outputs.commit }}](https://github.com/MoeKoeMusic/MoeKoeMusic/tree/${{ needs.generate-version.outputs.commit }})  " >> release-body.md
          echo "" >> release-body.md
          echo "**Full Changes**: https://github.com/MoeKoeMusic/MoeKoeMusic/compare/${{ needs.generate-version.outputs.prev_tag }}...${{ needs.generate-version.outputs.commit }}" >> release-body.md
          cat release-body.md | echo
      - name: release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.generate-version.outputs.fomatted_version }}
          body_path: release-body.md
          files: |
            dist_electron/MoeKoe_Music_Setup_${{ needs.generate-version.outputs.fomatted_version }}.exe
            ${{ steps.build.outputs.dist-mac-arm }}
            ${{ steps.build.outputs.dist-mac-intel }}
            ${{ steps.build.outputs.dist-linux }}
            ${{ steps.build.outputs.dist-linux-deb }}
